"""Write a project's `.codex/hooks.json` pointing at the bundled hooks.

Codex's hook protocol is Claude Code's: the same `hooks.json` shape
(`PreToolUse` / `SessionStart` / `PostToolUse`, a `matcher`, `type: "command"`
entries), the same JSON on stdin (`tool_name`, `tool_input.command`, `cwd`),
and the same verdicts — exit code 2 with the reason on stderr blocks, and a
`hookSpecificOutput.permissionDecision` on stdout is honoured. The shell tool
even reports itself to hooks as `Bash` (`codex-rs/core/src/tools/hook_names.rs`).
So the Python hooks that guard Claude Code sessions run under Codex unchanged;
the only thing to produce is the file that names them.

What differs, and why this file is generated rather than copied:

- `timeout` is SECONDS here. Claude Code's settings.json carried milliseconds
  by convention; a copied `5000` would be an 83-minute hook.
- The commands are absolute paths, including the interpreter — hooks run
  through `$SHELL -lc`, whose PATH may not be the one the MCP was installed
  from, and a hook that cannot start is a guard that silently is not there.
- Codex loads project hooks only after the user trusts them (a review prompt
  on the first launch that sees a new or changed hook file). Editing the file
  by hand invalidates that trust; regenerating it does too, on purpose.

Exposed as `co-scientist-local install-hooks --host codex [--dir .]`. Claude
Code needs no equivalent: its hooks live in `.claude/settings.json`, written by
`co-scientist link`.
"""
from __future__ import annotations

import json
import pathlib
import sys

_PKG_DIR = pathlib.Path(__file__).resolve().parent

# (event, matcher, [(hook file stem, timeout seconds)]) — the same three groups
# `co-scientist link` writes for Claude Code (packages/cli/.../link_cmd.py).
HOOK_GROUPS: list[tuple[str, str | None, list[tuple[str, int]]]] = [
    ("SessionStart", None, [("session_start", 5)]),
    ("PreToolUse", "Bash", [("pretool_block_ssh_nohup", 3),
                            ("pretool_cutadapt_lint", 2)]),
    ("PostToolUse", "mcp__scivo__*", [("post_tool", 3)]),
]


def _has_any_hook(d: pathlib.Path) -> bool:
    return d.is_dir() and any(c.suffix == ".py" and c.is_file() for c in d.iterdir())


def find_hooks_source() -> pathlib.Path | None:
    """Locate the hook scripts — bundled first, then the repo.

    Mirrors `skills_install.find_skills_source`: a wheel carries
    `co_scientist_local/hooks/`; an editable install or a clone resolves
    `packages/hooks` two levels up.
    """
    bundled = _PKG_DIR / "hooks"
    if _has_any_hook(bundled):
        return bundled
    repo_hooks = _PKG_DIR.parents[2] / "packages" / "hooks"
    if _has_any_hook(repo_hooks):
        return repo_hooks
    return None


def build_codex_hooks(source: pathlib.Path, python: str) -> dict:
    """The `.codex/hooks.json` document for hooks living in `source`."""
    events: dict[str, list] = {}
    for event, matcher, hooks in HOOK_GROUPS:
        group: dict = {}
        if matcher:
            group["matcher"] = matcher
        group["hooks"] = [
            {"type": "command",
             "command": f"{python} {source / (stem + '.py')}",
             "timeout": timeout}
            for stem, timeout in hooks
        ]
        events.setdefault(event, []).append(group)
    return {
        "description": "co-scientist hooks (generated by `co-scientist-local "
                       "install-hooks --host codex`; regenerate, do not edit)",
        "hooks": events,
    }


def install_hooks(
    project_dir: pathlib.Path | str = ".",
    *,
    host: str = "codex",
    source: pathlib.Path | None = None,
    python: str | None = None,
) -> dict:
    """Write `<project_dir>/.codex/hooks.json`. Returns a summary dict."""
    if host != "codex":
        raise ValueError(f"install-hooks supports host 'codex' only, not {host!r}")
    project_dir = pathlib.Path(project_dir).resolve()
    source = source or find_hooks_source()
    if source is None or not _has_any_hook(pathlib.Path(source)):
        return {"written": None, "source": None,
                "error": "no hooks source found (the ssh provenance guard will "
                         "not run under Codex)"}
    source = pathlib.Path(source).resolve()
    missing = [stem for _, _, hooks in HOOK_GROUPS for stem, _ in hooks
               if not (source / f"{stem}.py").is_file()]
    if missing:
        return {"written": None, "source": str(source),
                "error": f"hooks source is missing {', '.join(missing)}"}
    python = python or sys.executable
    dest = project_dir / ".codex" / "hooks.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(build_codex_hooks(source, python), indent=2) + "\n",
                    encoding="utf-8")
    return {"written": str(dest), "source": str(source), "python": python}


def cli(argv: list[str]) -> int:
    """`co-scientist-local install-hooks` — explicit, pre-launch install."""
    import argparse

    p = argparse.ArgumentParser(
        prog="co-scientist-local install-hooks",
        description="Write a project's .codex/hooks.json for the bundled hooks",
    )
    p.add_argument("--dir", default=".", help="project dir (default: cwd)")
    p.add_argument("--host", default="codex", choices=["codex"],
                   help="target host (only codex reads a hooks.json)")
    args = p.parse_args(argv)

    res = install_hooks(args.dir, host=args.host)
    if res.get("error"):
        print(f"✗ {res['error']}", file=sys.stderr)
        return 1
    print(f"✓ Wrote {res['written']}")
    print(f"  hooks: {res['source']}  interpreter: {res['python']}")
    print("  Codex will ask you to review and trust these hooks on the next launch.")
    return 0
