"""generate_image: call the configured ImageGenerator, store result in Storage.

Two output modes:
- `figure_number` provided → register as a Figure for the paper (calls
  figures.add_figure with the generated bytes written to a temp file).
- otherwise → store as a generic asset at
  `users/{uid}/papers/{slug}/assets/{filename}`. Skills can later promote
  an asset to a figure with `add_figure(local_path=...)`.

The ImageGenerator itself decides whether the call goes to the Cloud Function
(subscribed tier, server-side quota) or directly to Gemini with the user's
own key (free tier). The tool is unaware of the difference.
"""
from __future__ import annotations

import os
import pathlib
import tempfile

from ..backends.base import NotFound
from ..state import State
from ..util import new_id, now_iso
from . import figures as _figures
from .papers import _paper_path


def _project_image_style(state: State) -> str:
    """Project-wide image style defined in the web dashboard, stored at
    `projects/{pid}/settings/image_style` as a composed `style_text` string
    (preset phrase + the user's free text). Empty when unset.

    Applied automatically so every generated figure shares one look without
    the agent having to remember it on each call.
    """
    doc = state.backend.get_doc(state.project_path("settings", "image_style"))
    if not doc:
        return ""
    return (doc.get("style_text") or "").strip()


def generate_image(
    state: State,
    slug: str,
    *,
    prompt: str,
    figure_number: int | None = None,
    asset_filename: str | None = None,
    aspect_ratio: str = "1:1",
    model: str = "gpt-image-2",
    caption: str | None = None,
    overwrite: bool = False,
    apply_style: bool = True,
) -> dict:
    """Generate an image; either register it as a figure or store as an asset.

    The project's dashboard-defined image style (if any) is prepended to the
    prompt unless `apply_style=False`.

    Returns:
        - figure mode: the figure doc + {prompt, model, style_applied}
        - asset mode: {asset_id, blob_path, size_bytes, prompt, model, style_applied}
    """
    if state.backend.get_doc(_paper_path(state, slug)) is None:
        raise NotFound(f"paper not found: {slug!r} in project {state.project_id!r}")
    if not prompt or not prompt.strip():
        raise ValueError("prompt is required")

    style = _project_image_style(state) if apply_style else ""
    final_prompt = f"{prompt.strip()}\n\nVisual style: {style}" if style else prompt

    gen = state.require_image_gen()
    png = gen.generate(prompt=final_prompt, aspect_ratio=aspect_ratio, model=model)

    if figure_number is not None:
        # Spill to a temp file so add_figure's existing local_path path works.
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            tmp.write(png)
            tmp_path = tmp.name
        try:
            fig = _figures.add_figure(
                state, slug,
                figure_number=figure_number,
                title=f"Figure {figure_number}",
                caption=caption or prompt[:200],
                local_path=tmp_path,
                overwrite=overwrite,
                prompt=prompt,
                style_applied=style or None,
            )
        finally:
            os.unlink(tmp_path)
        return {
            "mode": "figure", "figure_number": figure_number,
            "blob_path": fig["blob_path"], "size_bytes": len(png),
            "prompt": prompt, "model": model,
            "style_applied": style or None,
            "dashboard_url": state.dashboard_url("papers", slug),
        }

    asset_id = new_id()
    name = asset_filename or f"img_{asset_id}.png"
    blob_path = state.project_path("papers", slug, "assets", name)
    state.backend.put_blob(blob_path, png)
    # Record an asset doc so the dashboard can list them
    doc_path = state.project_path("papers", slug, "assets", name)
    state.backend.set_doc(doc_path, {
        "asset_id": asset_id,
        "filename": name,
        "blob_path": blob_path,
        "size_bytes": len(png),
        "prompt": prompt,
        "model": model,
        "aspect_ratio": aspect_ratio,
        "style_applied": style or None,
        "created_at": now_iso(),
    })
    return {
        "mode": "asset", "asset_id": asset_id, "blob_path": blob_path,
        "size_bytes": len(png), "prompt": prompt, "model": model,
        "style_applied": style or None,
        "dashboard_url": state.dashboard_url("papers", slug),
    }


def list_assets(state: State, slug: str) -> list[dict]:
    """List image assets (non-figure generated images) for a paper."""
    if state.backend.get_doc(_paper_path(state, slug)) is None:
        raise NotFound(f"paper not found: {slug!r} in project {state.project_id!r}")
    pairs = state.backend.list_collection(state.project_path("papers", slug, "assets"))
    items = [data for _, data in pairs]
    items.sort(key=lambda x: x.get("created_at", ""), reverse=True)
    return items


def delete_asset(state: State, slug: str, asset_id_or_filename: str) -> bool:
    """Delete an asset by asset_id or filename."""
    if state.backend.get_doc(_paper_path(state, slug)) is None:
        raise NotFound(f"paper not found: {slug!r} in project {state.project_id!r}")
    for filename, data in state.backend.list_collection(
        state.project_path("papers", slug, "assets")
    ):
        if data.get("asset_id") == asset_id_or_filename or filename == asset_id_or_filename:
            blob_path = data.get("blob_path")
            doc_path = state.project_path("papers", slug, "assets", filename)
            if blob_path:
                state.backend.delete_blob(blob_path)
            state.backend.delete_doc(doc_path)
            return True
    return False
